CREATE TABLE `events` (
  `uuid` CHAR(36) NOT NULL DEFAULT (UUID()),
  `adult_name` VARCHAR(45) NOT NULL,
  `adult_email` VARCHAR(45) NOT NULL,
  `adult_phone` VARCHAR(45),
  `event_type` VARCHAR(45),
  `date` DATETIME,
  `time` CHAR(5),
  `guests` INT,
  `chosen_child` VARCHAR(45),
  `child_birthday` VARCHAR(45),
  `child_gender` VARCHAR(45),
  `child_color` VARCHAR(45),
  `theme` VARCHAR(45),
  `tablecloth_color` VARCHAR(45),
  `food` VARCHAR(45),
  `invitations` VARCHAR(45),
  `field_trip_school_name` VARCHAR(120),
  `field_trip_num_kids` INT,
  `field_trip_num_teachers` INT,
  `field_trip_age_range` INT,
  `field_trip_date_range` VARCHAR(45),
  `comments` VARCHAR(250),
  'paid' BOOLEAN,
  PRIMARY KEY (`uuid`)
);